export const works = [
	{
		id: 'todo',
		name: 'To Do List',
		imgsrc: '/todo.png',
		skill: 'React, React-dom, CSS',
		description: 'React로 제작한 To Do List로 CRUD를 구현하였습니다.',
		site: 'https://dong-han-kim.github.io/Todo-List/',
		github: 'https://github.com/Dong-Han-Kim/Todo-List.git',
	},
	{
		id: 'netflix',
		name: '영화 & 시리즈 소개',
		imgsrc: '/netflix.png',
		skill: 'React, Next.js, Tailwind css, Vercel, React Query,swiper, Typescript',
		description: 'Next.js와 React Query를 이용하고 만든 영화 & 시리즈 소개 사이트입니다.',
		site: 'https://netflix-six-nu.vercel.app/',
		github: 'https://github.com/Dong-Han-Kim/Netflix.git',
	},
	{
		id: 'dhmall',
		name: '쇼핑몰',
		imgsrc: '/dhmall.png',
		skill: 'React, Vercel, React Query, swiper, vanilla-extract, typescript, Firebase',
		description: 'React.js와 React Query를 이용하고 fake store api를 활용한 쇼핑몰입니다.',
		site: 'https://dong-han-kim.github.io/DHmall/',
		github: 'https://github.com/Dong-Han-Kim/DHmall.git',
	},
	{
		id: 'portfolio',
		name: '포트폴리오 사이트',
		imgsrc: '/portfolio.png',
		skill: 'React, Next.js, CSS module, Vercel',
		description: '저를 소개하기 위해 만든 현재 저의 포트폴리오입니다.',
		site: 'https://dhportfolio.vercel.app/',
		github: 'https://github.com/Dong-Han-Kim/myapp.git',
	},
];
